// pages/login.vue
<template>
  <client-only>
    <NavBar :navAdminMode="''" />
    <main class="ok-main ok-login-main">
      <section class="ok-login-card" aria-labelledby="okLoginTitle">
        <h1 id="okLoginTitle" class="ok-login-title">Welcome back</h1>
        <p class="ok-login-subtitle">Sign in to continue to Obsidian Key.</p>

        <form v-if="!showSuccess" class="ok-login-form" @submit.prevent="handleLogin">
          <label class="ok-login-label" for="okUsername">Username</label>
          <input
            id="okUsername"
            v-model.trim="formUsername"
            class="ok-login-input"
            type="text"
            autocomplete="username"
            required
          />

          <label class="ok-login-label" for="okPassword">Password</label>
          <input
            id="okPassword"
            v-model="formPassword"
            class="ok-login-input"
            type="password"
            autocomplete="current-password"
            required
          />

          <button class="ok-login-submit" type="submit" :disabled="isSubmitting">
            {{ isSubmitting ? "Signing in..." : "Log in" }}
          </button>

          <p v-if="errorText" class="ok-login-error">{{ errorText }}</p>
        </form>

        <div v-else class="ok-login-success">
          <h2 class="ok-success-title">Welcome, {{ fullName || username }}!</h2>
          <p class="ok-success-message">✓ You have successfully logged in</p>
          <div class="ok-user-data">
            <p><strong>Username:</strong> {{ username }}</p>
            <p v-if="userLevel >= 0"><strong>User Level:</strong> {{ userLevel }}</p>
            <p class="ok-redirect-notice">Redirecting to dashboard...</p>
          </div>
        </div>
      </section>
    </main>
    <Copyright />
  </client-only>
</template>

<script setup lang="ts">
import { useHead, useSeoMeta } from "@vueuse/head";

type LoginResponse = {
  accessToken?: string;
  token?: string;
  userLevel?: number;
  fullName?: string;
  username?: string;
};

const router = useRouter();

const formUsername = ref("");
const formPassword = ref("");
const errorText = ref("");
const isSubmitting = ref(false);
const showSuccess = ref(false);

const retries = useCookie<number>("retries", {
  sameSite: "none",
  secure: true,
  maxAge: 60 * 60,
});
retries.value = retries.value ?? 0;

const username = useCookie<string>("username", {
  sameSite: "none",
  secure: true,
  maxAge: 60 * 60 * 24,
});
username.value = username.value ?? "";

const accessToken = useCookie<string>("accessToken", {
  sameSite: "none",
  secure: true,
  maxAge: 60 * 60 * 24,
});
accessToken.value = accessToken.value ?? "";

const userLevel = useCookie<number>("userLevel", {
  sameSite: "none",
  secure: true,
  maxAge: 60 * 60 * 24,
});
userLevel.value = userLevel.value ?? -1;

const fullName = useCookie<string>("fullName", {
  sameSite: "none",
  secure: true,
  maxAge: 60 * 60 * 24,
});
fullName.value = fullName.value ?? "";

useSeoMeta({
  title: () => "Obsidian Key | Log in",
  description: () => "Sign in to Obsidian Key.",
  charset: "utf-8",
  viewport: "width=device-width, initial-scale=1.0",
});

useHead({
  link: [
    { rel: "icon", type: "image/png", href: "/logo.png" },
    { rel: "stylesheet", href: "/reset.css" },
    { rel: "stylesheet", href: "/custom.css" },
    { rel: "preconnect", href: "https://fonts.googleapis.com" },
    { rel: "preconnect", href: "https://fonts.gstatic.com", crossorigin: "" },
    {
      rel: "stylesheet",
      href: "https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,300..700;1,300..700&family=Noto+Sans+Display:ital,wght@0,100..900;1,100..900&display=swap",
    },
  ],
});

onMounted(() => {
  if (accessToken.value) {
    router.push("/");
  }
});

async function handleLogin() {
  if (isSubmitting.value) return;

  isSubmitting.value = true;
  errorText.value = "";

  try {
    const response = (await $fetch(`/api/login`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: {
        username: formUsername.value,
        password: formPassword.value,
      },
    })) as LoginResponse;

    const resolvedToken = response.accessToken ?? response.token ?? "";
    if (!resolvedToken) {
      throw new Error("Invalid login response.");
    }

    retries.value = 0;
    username.value = response.username || formUsername.value;
    accessToken.value = resolvedToken;
    userLevel.value = response.userLevel ?? 0;
    fullName.value = response.fullName ?? "";

    // Show success message
    showSuccess.value = true;

    // Wait 2 seconds before redirecting to allow user to see the welcome message
    setTimeout(() => {
      router.push("/");
    }, 2000);
  } catch (error: any) {
    retries.value = (retries.value ?? 0) + 1;
    const attempts = error?.data?.attempts || error?.data?.data?.attempts;
    const attemptPreview = Array.isArray(attempts) && attempts.length > 0 ? ` ${attempts[0]}` : "";
    errorText.value = (error?.data?.message || error?.message || "Unable to log in.") + attemptPreview;
  } finally {
    isSubmitting.value = false;
  }
}
</script>

<style>
.ok-login-main {
  min-height: calc(100vh - 110px);
  padding: 90px 16px 20px;
  display: flex;
  align-items: center;
  justify-content: center;
}

.ok-login-card {
  width: min(420px, 100%);
  padding: 28px;
  border-radius: 12px;
  background: #ffffff;
  border: 1px solid #d9dce2;
  box-shadow: 0 16px 40px rgba(12, 23, 38, 0.08);
}

.ok-login-title {
  font-size: 1.8rem;
  line-height: 1.2;
  font-family: "Cormorant Garamond", Georgia, serif;
  color: #0b0c10;
}

.ok-login-subtitle {
  margin-top: 6px;
  color: #535b67;
}

.ok-login-form {
  margin-top: 20px;
}

.ok-login-label {
  margin-top: 12px;
  margin-bottom: 6px;
  display: block;
  font-size: 0.9rem;
  color: #21252b;
}

.ok-login-input {
  width: 100%;
  padding: 11px 12px;
  font-size: 1rem;
  border-radius: 8px;
  border: 1px solid #c9ced8;
}

.ok-login-input:focus {
  outline: 2px solid #3a3f78;
  outline-offset: 1px;
}

.ok-login-submit {
  margin-top: 18px;
  width: 100%;
  padding: 12px;
  border: 0;
  border-radius: 8px;
  color: #fff;
  background: #3a3f78;
  cursor: pointer;
}

.ok-login-submit:disabled {
  cursor: not-allowed;
  opacity: 0.75;
}

.ok-login-error {
  margin-top: 12px;
  color: #b2162f;
  font-size: 0.9rem;
}

.ok-login-success {
  margin-top: 20px;
  padding: 20px;
  border-radius: 8px;
  background: #f0fdf4;
  border: 1px solid #86efac;
  text-align: center;
}

.ok-success-title {
  font-size: 1.5rem;
  line-height: 1.2;
  font-family: "Cormorant Garamond", Georgia, serif;
  color: #166534;
  margin: 0 0 12px 0;
}

.ok-success-message {
  font-size: 1.1rem;
  color: #15803d;
  margin: 0 0 16px 0;
  font-weight: 500;
}

.ok-user-data {
  background: #ffffff;
  border: 1px solid #bbf7d0;
  border-radius: 6px;
  padding: 16px;
  text-align: left;
  margin-top: 16px;
}

.ok-user-data p {
  margin: 8px 0;
  color: #15803d;
  font-size: 0.95rem;
}

.ok-user-data strong {
  color: #166534;
}

.ok-redirect-notice {
  margin-top: 12px;
  font-size: 0.9rem;
  color: #059669;
  font-style: italic;
}
</style>

// src/app/login/page.tsx
"use client";

import React, { useState, useEffect } from "react";
import { useRouter } from "next/navigation";
import Copyright from "@/components/Copyright";

export default function LoginPage() {
  const router = useRouter();
  const [formUsername, setFormUsername] = useState("");
  const [formPassword, setFormPassword] = useState("");
  const [errorText, setErrorText] = useState("");
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [showSuccess, setShowSuccess] = useState(false);
  const [fullName, setFullName] = useState("");

  useEffect(() => {
    // Check if already logged in
    const match = document.cookie.match(/(^| )accessToken=([^;]+)/);
    if (match && match[2]) {
      router.push("/");
    }
  }, [router]);

  const setCookie = (name: string, value: string) => {
    const maxAge = 60 * 60 * 24; // 1 day
    document.cookie = `${name}=${encodeURIComponent(value)}; path=/; max-age=${maxAge}; SameSite=None; Secure`;
  };

  const handleLogin = async (e: React.FormEvent) => {
    e.preventDefault();
    if (isSubmitting) return;

    setIsSubmitting(true);
    setErrorText("");

    try {
      const res = await fetch("/api/login", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          username: formUsername,
          password: formPassword,
        }),
      });

      const data = await res.json();

      if (!res.ok) {
        throw new Error(data.message || "Unable to log in.");
      }

      const resolvedToken = data.accessToken || data.token || "";
      if (!resolvedToken) {
        throw new Error("Invalid login response.");
      }

      // Save cookies
      setCookie("username", data.username || formUsername);
      setCookie("accessToken", resolvedToken);
      setCookie("userLevel", String(data.userLevel ?? 0));
      setCookie("fullName", data.fullName || "");

      setFullName(data.fullName || data.username || formUsername);
      setShowSuccess(true);

      // Redirect after 2 seconds
      setTimeout(() => {
        router.push("/");
      }, 1500);
    } catch (err: any) {
      setErrorText(err.message || "An unexpected error occurred.");
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <>
      <header className="ok-navbar">
        <div className="ok-nav-left">
          <div className="ok-nav-home">
            <img src="/logo.png" width={24} height={24} className="ok-nav-logo" alt="Logo" />
              <span>Pathuro</span>
          </div>
        </div>
      </header>

      <main className="ok-main ok-login-main ok-fade-in">
        <section className="ok-login-card" aria-labelledby="okLoginTitle">
          <h1 id="okLoginTitle" className="ok-login-title">Welcome back</h1>
          <p className="ok-login-subtitle">Sign in to continue to Pathuro Course Matcher.</p>

          {!showSuccess ? (
            <form className="ok-login-form" onSubmit={handleLogin}>
              <div style={{ marginBottom: "16px" }}>
                <label className="ok-login-label" htmlFor="okUsername">
                  Username
                </label>
                <input
                  id="okUsername"
                  value={formUsername}
                  onChange={(e) => setFormUsername(e.target.value)}
                  className="ok-login-input ok-input"
                  type="text"
                  autoComplete="username"
                  required
                  placeholder="e.g. student or admin"
                />
              </div>

              <div style={{ marginBottom: "20px" }}>
                <label className="ok-login-label" htmlFor="okPassword">
                  Password
                </label>
                <input
                  id="okPassword"
                  value={formPassword}
                  onChange={(e) => setFormPassword(e.target.value)}
                  className="ok-login-input ok-input"
                  type="password"
                  autoComplete="current-password"
                  required
                  placeholder="e.g. student or admin"
                />
              </div>

              <button
                className="ok-login-submit ok-btn ok-btn-primary"
                type="submit"
                disabled={isSubmitting}
                style={{ width: "100%", padding: "12px" }}
              >
                {isSubmitting ? "Signing in..." : "Log in"}
              </button>

              {errorText && <p className="ok-login-error">{errorText}</p>}

              <div 
                style={{ 
                  marginTop: "20px", 
                  padding: "12px", 
                  background: "#f1f5f9", 
                  borderRadius: "8px", 
                  fontSize: "0.85em",
                  color: "#64748b",
                  border: "1px solid #e2e8f0"
                }}
              >
                💡 <strong>Demo Accounts Available:</strong>
                <ul style={{ paddingLeft: "16px", marginTop: "4px" }}>
                  <li>Student access: use <strong>student</strong> / <strong>student</strong></li>
                  <li>Admin access: use <strong>admin</strong> / <strong>admin</strong></li>
                </ul>
              </div>
            </form>
          ) : (
            <div className="ok-login-success ok-fade-in">
              <h2 className="ok-success-title">Welcome, {fullName}!</h2>
              <p className="ok-success-message">✓ You have successfully logged in</p>
              <div className="ok-user-data">
                <p><strong>Username:</strong> {formUsername}</p>
                <p className="ok-redirect-notice">Redirecting to course matcher...</p>
              </div>
            </div>
          )}
        </section>
      </main>
      
      <Copyright />

      <style jsx>{`
        .ok-login-main {
          min-height: calc(100vh - 120px);
          display: flex;
          align-items: center;
          justify-content: center;
          padding-top: 120px;
        }
        .ok-login-card {
          width: min(420px, 100%);
          padding: 32px;
          border-radius: 16px;
          background: #ffffff;
          border: 1px solid var(--card-border);
          box-shadow: 0 20px 40px -10px rgba(15, 23, 42, 0.1);
        }
        .ok-login-title {
          font-size: 2rem;
          line-height: 1.2;
          font-family: var(--font-heading);
          color: var(--text-main);
          margin-bottom: 6px;
        }
        .ok-login-subtitle {
          font-size: 0.95rem;
          color: var(--text-muted);
          margin-bottom: 24px;
        }
        .ok-login-label {
          display: block;
          font-size: 0.9rem;
          font-weight: 600;
          color: #334155;
          margin-bottom: 6px;
        }
        .ok-login-input {
          width: 100%;
        }
        .ok-login-error {
          margin-top: 14px;
          color: var(--danger);
          font-size: 0.9rem;
          font-weight: 500;
          background: var(--danger-light);
          padding: 10px;
          border-radius: 8px;
          border: 1px solid rgba(239, 68, 68, 0.2);
        }
        .ok-login-success {
          padding: 10px 0;
          text-align: center;
        }
        .ok-success-title {
          font-size: 1.8rem;
          font-family: var(--font-heading);
          color: var(--success);
          margin-bottom: 8px;
        }
        .ok-success-message {
          font-weight: 600;
          color: var(--success);
          margin-bottom: 20px;
        }
        .ok-user-data {
          background: #f8fafc;
          border: 1px solid var(--card-border);
          border-radius: 12px;
          padding: 16px;
          text-align: left;
        }
        .ok-user-data p {
          margin-bottom: 8px;
        }
        .ok-redirect-notice {
          margin-top: 12px;
          font-size: 0.85em;
          color: var(--primary);
          font-style: italic;
        }
      `}</style>
    </>
  );
}
